### ISSUE TITLE
Import Error: can't import name gcd from fractions

### ISSUE THREAD

**Issue by wyanren** [GPZ-Bioinfo/tmap#15]
When I run the script of "Network_generator.py" or "SAFE_analysis.py", I met this report:

Import Error: cannot import name 'gcd' from 'fractions' 

But when I want to troubleshoot that, others who also meet this error claimed that I should update the "networkx" to ≥ 2.5.1.
https://stackoverflow.com/questions/66174862/import-error-cant-import-name-gcd-from-fractions
https://stackoverflow.com/questions/67165725/ubuntu-error-cannot-import-name-gcd-from-fractions

However the tmap 1.2 requires networkx=2.2. I am very confused about this bug. 
Hope you help me with that.

**Comment by 444thLiao** [comment]
Since the script "Network_generator.py" doesn't import `fractions `or `gcd `directly, it might be caused by some inter-packages conflicts. 
I think it would be easier to trace the error by uploading a screenshot or the full text reported by the python. It would tell us which line this error was raised at.

**Comment by wyanren** [comment]
![safe](https://user-images.githubusercontent.com/66079632/144544333-56ecc601-1213-49d6-b544-db18f0be9d62.png)
![network](https://user-images.githubusercontent.com/66079632/144544346-8f50cb37-c1b2-4009-a653-a546f412e77b.png)

Sorry, since the server is one-way, I can't export to copy the error report file, so I screenshot them.

**Comment by 444thLiao** [comment]
That's ok. A Screenshot is enough.

So the problem actually is caused by the conflicts between networkx and python3.9.
In general, update/downgrade either one is ok to solve the problem as the links said.  But the fixed version of networkx is because updating the networkx would raise another error during the network visualization. 

Thus, I think it's better to use **python3.8** and install related packages as the `requirement` said would be fine.

I have tested it with python3.8. The `gcd` function has not yet moved to the `math` package. So it would be fine in this step.

**Comment by wyanren** [comment]
I create a new environment with **python3.8** using conda, and re-install tmap2.
And the bug turns to be solved! 

Thanks for your advice, enjoy your weekend!
